language: java

jdk:
 - oraclejdk8

os:
  - linux

cache:
  directories:
  - $HOME/.gradle

install: echo "skip 'gradle assemble' step"

build: echo "skip 'gradle check' step"

script:
 - ./gradlew clean buildAll

